# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: About
    url: about
    weight: 10
  - name: Media
    url: media
    weight: 20
  - name: Publications
    url: publication
    weight: 30
  - name: Events
    url: event
    weight: 40
  - name: People
    url: people
    weight: 50
  - name: Contact
    url: contact
    weight: 60
